site_name: pybrook
site_dir: docs_html
use_directory_urls: false

theme:
  name: "material"
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: white
      accent: pink
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/mkdocstrings.css

extra:
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
      guess_lang: false
  - admonition
  - footnotes
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - literate-nav:
      nav_file: SUMMARY.md
  - search
  - autorefs
  - gen-files:
      scripts:
      - docs/scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: True
            show_bases: True
            filters:
              - "!^__config__"
              - "!^__json_encoder__"
              - "!^__fields__"
              - "!^__post_root_validators__"
              - "!^__pre_root_validators__"
              - "!^__signature__"
              - "!^__slots__"
              - "!^__validators__"
              - "!^__class_vars__"
              - "!^__private__attributes__"
              - "!^__schema_cache__"
              - "!^__custom_root_type__"
              - "!^__doc__"
              - "!^__private_attributes__"