name: Documentation

on:
  push:
    branches:
      - master


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Publish docs
        run: poetry run mkdocs gh-deploy