name: Documentation

on:
  push:
    branches:
      - master


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
      - name: Install development dependencies
        run: poetry install --group dev
      - name: Publish docs
        run: poetry run mkdocs gh-deploy