name: Documentation

on:
  push:
    branches:
      - master


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pdm-project/setup-pdm@v4
      - name: Install development dependencies
        run: pdm install -G docs
      - name: Publish docs
        run: pdm run mkdocs gh-deploy